name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.FIREBASE_ENVIRONMENT }} | base64 -d >> src/environments/environment.prod.ts
      - run: npm ci 
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSF_WEBSITE }}'
          projectId: jsf-website
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
